sudo: false
language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
before_install:
- pip install --upgrade pip
install:
- pip install --upgrade coverage coveralls pytest pytest-cov
- pip install python-louvain
- pip install .
script:
- python -m pytest --cov=linkpred
after_success: coveralls
env:
  # PyPI token split into $DPASS1/$DPASS2 (https://github.com/travis-ci/travis.rb/issues/687).
  - secure: "QZEydG12Cx0fNZ6x9eGuEvnbcr83mvgTmfXlCYZ7sxN+p7TH95xePwf2xsnecDgv6F3tDGkkGhDbbk+MC1I7RqP6aXLOpBjc7oIx2Q7r1b+JJFhuStJajkUYH0F9LU6ndF5f8vhEbC8pP2f3i0cSTW8XnFLpLzCT4xjz2CqPmpw="
  - secure: "H+ltcXoRttogMVMIDAPu2XG/JeUFD5cMTpuYVbor4q4fYVLgT9tlHnPivPrUjdr+KRRBQl5D20X885gcMFyTW/Qg6lrG4SF4rkd0ud0RLXFhmen4VVmszqn4LL24vKBHqhHJ/VCKQRfVYaobzrtmysUSbP18eJXjTzjlKxU8GLg="
deploy:
  provider: pypi
  user: __token__
  password: $DPASS1$DPASS2
  skip_existing: true
  on:
    tags: true
